### ISSUE TITLE
Unable to set cmake_root_markers to empty list

### ISSUE THREAD

**Issue by anupambhatnagar** [cdelledonne/vim-cmake#38]
### Bug description
Unable to set `cmake_root_markers` to empty list via `.vimrc`. If `let g:cmake_root_markers = []` is executed after launching vim, then the correct value can be set.

### To Reproduce
1. Add the following line in your `.vimrc` or `init.vim` file:
``` 
let g:cmake_root_markers = []
```
2. Save the file and restart vim
3. Execute `let g:cmake_root_markers` in vim.
4. The output is `['.git', '.svn']` instead of `[]`

### Expected behavior
The output should be an empty list instead of the default list. 

### Behavior with minimal `.vimrc`
I am able to reproduce this issue with a minimal `.vimrc`

### Other info
- OS: Mac OS X 12.3
- Vim/Neovim version: Neovim 0.6.0
- Vim-CMake version (5th line in `:help cmake`): 0.6.2

### Additional context
For the time being, I have modified the values in the list [here](https://github.com/cdelledonne/vim-cmake/blob/d82f2a185b17f8390877a8bc4d112dadabe3cea6/plugin/cmake.vim#L38) to an empty list and installed your awesome plugin using the modified code. This issue is probably due to `config_vars` overriding the options set in the `.vimrc` file, but I could be wrong.

**Comment by cdelledonne** [comment]
Hi, thanks a lot for reporting this. And happy to hear you find the plugin useful :)

Yes this is indeed not the expected behavior. For some reason, when the user sets the value of a configuration variable to an empty list, that list is extended with the default configuration values. See line 47 from `plugin/cmake.vim`
https://github.com/cdelledonne/vim-cmake/blob/d82f2a185b17f8390877a8bc4d112dadabe3cea6/plugin/cmake.vim#L41-L50

I believe this list extension can be removed altogether. This should solve the issue.

Would you be interested in preparing a PR for this? If so, just look at [CONTRIBUTING.md](https://github.com/cdelledonne/vim-cmake/blob/master/CONTRIBUTING.md) and you should be good to go.
