### ISSUE TITLE
Support additional statusline plugins

### ISSUE THREAD

**Issue by cdelledonne** [cdelledonne/vim-cmake#46]
At the moment, only [vim-airline](https://github.com/vim-airline/vim-airline) is supported. Add support for additional statusline plugins, possibly also those written in Lua for Neovim.

**Comment by marwing** [comment]
Hi,
A good first step might be to provide an option to disable vim-cmake's custom statusline.

Currently, vim-cmake forcibly sets the `statusline` option (locally) in its terminal window ([here](https://github.com/cdelledonne/vim-cmake/blob/07fb73ee0d0c89dd608f1ed5f691bc151406558a/autoload/cmake/terminal.vim#L251-L253)). This overrides other plugins' statuslines, even if they have a custom configuration for vim-cmake. I noticed this when I switched from vim-airline to [lualine.nvim](https://github.com/nvim-lualine/lualine.nvim) (one of those written in lua, as the name implies) and wrote my own extension that wouldn't work, because lualine's statusline got overwritten by vim-cmake's.
I don't know what exactly vim-airline does for it to work, but I would assume they reset the `statusline` option on BufEnter or something.

To solve this for now, I would suggest adding a new configuration variable, to disable vim-cmake's statusline and let people figure out how to write a custom statusline for vim-cmake in their setup. The variable could be named something like `g:cmake_statusline_disable` and would stop this plugin from setting a custom `statusline`.
If by support for other statusline plugins you mean actual extensions for those plugins, these could be easily added in addition to this and may even require this or a similar change.

For reference, my lualine extension for vim-cmake can be found here: https://gitlab.com/marwing/dotfiles/-/blob/19816edadfdc6338101ae7845cc228c59550c7e7/.config/nvim/lua/lualine/extensions/vimcmake.lua
This currently only works, if you manually set `statusline` back to lualine's in the cmake build window or if you comment out the aforementioned lines in terminal.vim. If I do it works great though.

BTW, thanks for your work on this plugin, I love it.
